name: test-channels
base: core18
version: '1.0'
summary: Test snap that has a different version in each channel
description: |
  Test snap that has a different version in each channel.

grade: stable
confinement: strict

parts:
  my-part:
    plugin: nil
